"""enquiry

Revision ID: b244bc02bcc4
Revises: 
Create Date: 2024-09-22 16:40:38.204193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b244bc02bcc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry_status',
    sa.Column('enquiry_status_id', sa.Integer(), nullable=False),
    sa.Column('enquiry_status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('enquiry_status_id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))

    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('enquiry_status_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'enquiry_status', ['enquiry_status_id'], ['enquiry_status_id'])
        batch_op.create_foreign_key(None, 'user', ['email'], ['email'])
        batch_op.create_foreign_key(None, 'user', ['first_name'], ['first_name'])
        batch_op.create_foreign_key(None, 'course', ['course_name'], ['course_name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('enquiry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enquiry_status_id')
        batch_op.drop_column('email')
        batch_op.drop_column('first_name')
        batch_op.drop_column('course_name')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    op.drop_table('enquiry_status')
    # ### end Alembic commands ###
