"""empty message

Revision ID: fb970148b962
Revises: b244bc02bcc4
Create Date: 2024-09-23 15:14:27.362591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'fb970148b962'
down_revision = 'b244bc02bcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry_status',
    sa.Column('enquiry_status_id', sa.Integer(), nullable=False),
    sa.Column('enquiry_status', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('enquiry_status_id')
    )
    op.create_table('enquiry',
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('enquiry_text', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('enquiry_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['enquiry_status'], ['enquiry_status.enquiry_status_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('enquiry_id')
    )
    op.drop_table('Enquiry')
    op.drop_table('Enquiry_status')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=300, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(getdate())'))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('icon',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    op.create_table('Enquiry_status',
    sa.Column('enquiry_status_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('enquiry_status', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('enquiry_status_id', name='PK__Enquiry___FD4011CF12B92782')
    )
    op.create_table('Enquiry',
    sa.Column('enquiry_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enquiry_text', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('response', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('enquiry_status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], name='FK_Enquiry_Course'),
    sa.ForeignKeyConstraint(['enquiry_status'], ['Enquiry_status.enquiry_status_id'], name='FK_Enquiry_EnquiryStatus'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='FK_Enquiry_User'),
    sa.PrimaryKeyConstraint('enquiry_id', name='PK__Enquiry__57CC01B3D8482368')
    )
    op.drop_table('enquiry')
    op.drop_table('enquiry_status')
    # ### end Alembic commands ###
